tab<-table(nhdsdatadf$Diagnosis.Code.1)
tab_s<-sort(tab)
top_10<-tail(names(tab_s), 10)
diag1<-subset(nhdsdatadf, Diagnosis.Code.1 %in% top_10)
nhdsdatadf$Diagnosis.Code.1 <- factor(nhdsdatadf$Diagnosis.Code.1, levels = rev(top_10))
ggplot(data = nhdsdatadf, aes(x=Diagnosis.Code.1))+geom_histogram()+theme(axis.text.x=element_text(angle = 45, vjust = 0.5))

tab<-table(nhdsdatadf$Diagnosis.Code.2)
tab_s<-sort(tab)
top_10<-tail(names(tab_s), 10)
diag1<-subset(nhdsdatadf, Diagnosis.Code.2 %in% top_10)
nhdsdatadf$Diagnosis.Code.2 <- factor(nhdsdatadf$Diagnosis.Code.2, levels = rev(top_10))
ggplot(data = nhdsdatadf, aes(x=Diagnosis.Code.2))+geom_histogram()+theme(axis.text.x=element_text(angle = 45, vjust = 0.5))

tab<-table(nhdsdatadf$Diagnosis.Code.3)
tab_s<-sort(tab)
top_10<-tail(names(tab_s), 10)
diag1<-subset(nhdsdatadf, Diagnosis.Code.3 %in% top_10)
nhdsdatadf$Diagnosis.Code.3 <- factor(nhdsdatadf$Diagnosis.Code.3, levels = rev(top_10))
ggplot(data = nhdsdatadf, aes(x=Diagnosis.Code.3))+geom_histogram()+theme(axis.text.x=element_text(angle = 45, vjust = 0.5))

tab<-table(nhdsdatadf$Diagnosis.Code.4)
tab_s<-sort(tab)
top_10<-tail(names(tab_s), 10)
diag1<-subset(nhdsdatadf, Diagnosis.Code.4 %in% top_10)
nhdsdatadf$Diagnosis.Code.4 <- factor(nhdsdatadf$Diagnosis.Code.4, levels = rev(top_10))
ggplot(data = nhdsdatadf, aes(x=Diagnosis.Code.4))+geom_histogram()+theme(axis.text.x=element_text(angle = 45, vjust = 0.5))

tab<-table(nhdsdatadf$Diagnosis.Code.5)
tab_s<-sort(tab)
top_10<-tail(names(tab_s), 10)
diag1<-subset(nhdsdatadf, Diagnosis.Code.5 %in% top_10)
nhdsdatadf$Diagnosis.Code.5 <- factor(nhdsdatadf$Diagnosis.Code.5, levels = rev(top_10))
ggplot(data = nhdsdatadf, aes(x=Diagnosis.Code.5))+geom_histogram()+theme(axis.text.x=element_text(angle = 45, vjust = 0.5))

tab<-table(nhdsdatadf$Diagnosis.Code.6)
tab_s<-sort(tab)
top_10<-tail(names(tab_s), 10)
diag1<-subset(nhdsdatadf, Diagnosis.Code.6 %in% top_10)
nhdsdatadf$Diagnosis.Code.6 <- factor(nhdsdatadf$Diagnosis.Code.6, levels = rev(top_10))
ggplot(data = nhdsdatadf, aes(x=Diagnosis.Code.6))+geom_histogram()+theme(axis.text.x=element_text(angle = 45, vjust = 0.6))

tab<-table(nhdsdatadf$Diagnosis.Code.7)
tab_s<-sort(tab)
top_10<-tail(names(tab_s), 10)
diag1<-subset(nhdsdatadf, Diagnosis.Code.7 %in% top_10)
nhdsdatadf$Diagnosis.Code.7 <- factor(nhdsdatadf$Diagnosis.Code.7, levels = rev(top_10))
ggplot(data = nhdsdatadf, aes(x=Diagnosis.Code.7))+geom_histogram(binwidth=0.1)+theme(axis.text.x=element_text(angle = 45, vjust = 0.7))


library("knitr")
